[package]
name = "firefly-bulb"
version = "0.2.0"
edition = "2024"
rust-version = "1.91.0"

[dependencies]
firefly-rust = { version = "0.10.0", features = ["alloc", "talc"] }
# bulb-parser = { path = "../bulb-parser" }
bulb-parser = "0.2.0"

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true      # Enable link-time optimization
