[package]
name = "firefly-bulb"
version = "0.3.0"
edition = "2024"
rust-version = "1.95.0"

[dependencies]
firefly-rust = { version = "0.14.0", features = ["talc"] }
bulb-parser = "0.3.0"

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "s" # Optimize for speed.
lto = true      # Enable link-time optimization
